### ISSUE TITLE
ProcessImages script malfunctions on Windows 10

### ISSUE THREAD

**Issue by SpaceYoshi** [Promptus-Imperii/Promptus-Imperii.github.io#49]
[Windows PowerShell.txt](https://github.com/user-attachments/files/18219428/Windows.PowerShell.txt)
Seems like a permission problem. I've also tried running `npm run process-images` in PowerShell as administrator.

**Comment by TeaDrinkingProgrammer** [comment]
I got it to work in the end, it probably had to do with:
- Updating to the latest node version `nvm install lts`, then `nvm use lts`
- Closing VScode while running it (because it locks the files)
- If that doesn't work: reboot or `npm ci`
